export interface City {
  city: string;
  flag: string;
  label: string;
}

export const ALL_CITIES: City[] = [
  // ── TÜRKİYE
  { city: 'Istanbul', flag: '🇹🇷', label: 'İstanbul, Türkiye' },
  { city: 'Ankara', flag: '🇹🇷', label: 'Ankara, Türkiye' },
  { city: 'Izmir', flag: '🇹🇷', label: 'İzmir, Türkiye' },
  { city: 'Antalya', flag: '🇹🇷', label: 'Antalya, Türkiye' },
  { city: 'Bodrum', flag: '🇹🇷', label: 'Bodrum, Türkiye' },
  { city: 'Alanya', flag: '🇹🇷', label: 'Alanya, Türkiye' },
  { city: 'Marmaris', flag: '🇹🇷', label: 'Marmaris, Türkiye' },
  { city: 'Fethiye', flag: '🇹🇷', label: 'Fethiye, Türkiye' },
  { city: 'Cappadocia', flag: '🇹🇷', label: 'Kapadokya, Türkiye' },
  { city: 'Trabzon', flag: '🇹🇷', label: 'Trabzon, Türkiye' },
  { city: 'Bursa', flag: '🇹🇷', label: 'Bursa, Türkiye' },
  { city: 'Gaziantep', flag: '🇹🇷', label: 'Gaziantep, Türkiye' },
  { city: 'Konya', flag: '🇹🇷', label: 'Konya, Türkiye' },
  { city: 'Adana', flag: '🇹🇷', label: 'Adana, Türkiye' },
  { city: 'Eskisehir', flag: '🇹🇷', label: 'Eskişehir, Türkiye' },
  { city: 'Kusadasi', flag: '🇹🇷', label: 'Kuşadası, Türkiye' },
  { city: 'Cesme', flag: '🇹🇷', label: 'Çeşme, Türkiye' },
  { city: 'Pamukkale', flag: '🇹🇷', label: 'Pamukkale, Türkiye' },
  { city: 'Kayseri', flag: '🇹🇷', label: 'Kayseri, Türkiye' },
  { city: 'Diyarbakir', flag: '🇹🇷', label: 'Diyarbakır, Türkiye' },
  { city: 'Erzurum', flag: '🇹🇷', label: 'Erzurum, Türkiye' },
  { city: 'Canakkale', flag: '🇹🇷', label: 'Çanakkale, Türkiye' },
  { city: 'Safranbolu', flag: '🇹🇷', label: 'Safranbolu, Türkiye' },

  // ── AVRUPA — Batı
  { city: 'London', flag: '🇬🇧', label: 'Londra, İngiltere' },
  { city: 'Manchester', flag: '🇬🇧', label: 'Manchester, İngiltere' },
  { city: 'Edinburgh', flag: '🇬🇧', label: 'Edinburgh, İskoçya' },
  { city: 'Paris', flag: '🇫🇷', label: 'Paris, Fransa' },
  { city: 'Nice', flag: '🇫🇷', label: 'Nice, Fransa' },
  { city: 'Lyon', flag: '🇫🇷', label: 'Lyon, Fransa' },
  { city: 'Marseille', flag: '🇫🇷', label: 'Marsilya, Fransa' },
  { city: 'Bordeaux', flag: '🇫🇷', label: 'Bordeaux, Fransa' },
  { city: 'Berlin', flag: '🇩🇪', label: 'Berlin, Almanya' },
  { city: 'Munich', flag: '🇩🇪', label: 'Münih, Almanya' },
  { city: 'Hamburg', flag: '🇩🇪', label: 'Hamburg, Almanya' },
  { city: 'Frankfurt', flag: '🇩🇪', label: 'Frankfurt, Almanya' },
  { city: 'Cologne', flag: '🇩🇪', label: 'Köln, Almanya' },
  { city: 'Amsterdam', flag: '🇳🇱', label: 'Amsterdam, Hollanda' },
  { city: 'Rotterdam', flag: '🇳🇱', label: 'Rotterdam, Hollanda' },
  { city: 'Brussels', flag: '🇧🇪', label: 'Brüksel, Belçika' },
  { city: 'Bruges', flag: '🇧🇪', label: 'Brugge, Belçika' },
  { city: 'Madrid', flag: '🇪🇸', label: 'Madrid, İspanya' },
  { city: 'Barcelona', flag: '🇪🇸', label: 'Barselona, İspanya' },
  { city: 'Seville', flag: '🇪🇸', label: 'Sevilla, İspanya' },
  { city: 'Valencia', flag: '🇪🇸', label: 'Valensiya, İspanya' },
  { city: 'Malaga', flag: '🇪🇸', label: 'Malaga, İspanya' },
  { city: 'Ibiza', flag: '🇪🇸', label: 'İbiza, İspanya' },
  { city: 'Lisbon', flag: '🇵🇹', label: 'Lizbon, Portekiz' },
  { city: 'Porto', flag: '🇵🇹', label: 'Porto, Portekiz' },
  { city: 'Rome', flag: '🇮🇹', label: 'Roma, İtalya' },
  { city: 'Milan', flag: '🇮🇹', label: 'Milano, İtalya' },
  { city: 'Venice', flag: '🇮🇹', label: 'Venedik, İtalya' },
  { city: 'Florence', flag: '🇮🇹', label: 'Floransa, İtalya' },
  { city: 'Naples', flag: '🇮🇹', label: 'Napoli, İtalya' },
  { city: 'Amalfi', flag: '🇮🇹', label: 'Amalfi, İtalya' },
  { city: 'Palermo', flag: '🇮🇹', label: 'Palermo, İtalya' },
  { city: 'Turin', flag: '🇮🇹', label: 'Turin, İtalya' },
  { city: 'Zurich', flag: '🇨🇭', label: 'Zürih, İsviçre' },
  { city: 'Geneva', flag: '🇨🇭', label: 'Cenevre, İsviçre' },
  { city: 'Bern', flag: '🇨🇭', label: 'Bern, İsviçre' },
  { city: 'Vienna', flag: '🇦🇹', label: 'Viyana, Avusturya' },
  { city: 'Salzburg', flag: '🇦🇹', label: 'Salzburg, Avusturya' },
  { city: 'Innsbruck', flag: '🇦🇹', label: 'Innsbruck, Avusturya' },

  // ── AVRUPA — Kuzey
  { city: 'Stockholm', flag: '🇸🇪', label: 'Stockholm, İsveç' },
  { city: 'Gothenburg', flag: '🇸🇪', label: 'Göteborg, İsveç' },
  { city: 'Oslo', flag: '🇳🇴', label: 'Oslo, Norveç' },
  { city: 'Bergen', flag: '🇳🇴', label: 'Bergen, Norveç' },
  { city: 'Copenhagen', flag: '🇩🇰', label: 'Kopenhag, Danimarka' },
  { city: 'Helsinki', flag: '🇫🇮', label: 'Helsinki, Finlandiya' },
  { city: 'Reykjavik', flag: '🇮🇸', label: 'Reykjavik, İzlanda' },
  { city: 'Tallinn', flag: '🇪🇪', label: 'Tallinn, Estonya' },
  { city: 'Riga', flag: '🇱🇻', label: 'Riga, Letonya' },
  { city: 'Vilnius', flag: '🇱🇹', label: 'Vilnius, Litvanya' },

  // ── AVRUPA — Orta & Doğu
  { city: 'Prague', flag: '🇨🇿', label: 'Prag, Çek Cumhuriyeti' },
  { city: 'Budapest', flag: '🇭🇺', label: 'Budapeşte, Macaristan' },
  { city: 'Warsaw', flag: '🇵🇱', label: 'Varşova, Polonya' },
  { city: 'Krakow', flag: '🇵🇱', label: 'Krakow, Polonya' },
  { city: 'Gdansk', flag: '🇵🇱', label: 'Gdansk, Polonya' },
  { city: 'Bucharest', flag: '🇷🇴', label: 'Bükreş, Romanya' },
  { city: 'Sofia', flag: '🇧🇬', label: 'Sofya, Bulgaristan' },
  { city: 'Belgrade', flag: '🇷🇸', label: 'Belgrad, Sırbistan' },
  { city: 'Zagreb', flag: '🇭🇷', label: 'Zagreb, Hırvatistan' },
  { city: 'Dubrovnik', flag: '🇭🇷', label: 'Dubrovnik, Hırvatistan' },
  { city: 'Split', flag: '🇭🇷', label: 'Split, Hırvatistan' },
  { city: 'Ljubljana', flag: '🇸🇮', label: 'Ljubljana, Slovenya' },
  { city: 'Bratislava', flag: '🇸🇰', label: 'Bratislava, Slovakya' },
  { city: 'Kyiv', flag: '🇺🇦', label: 'Kyiv, Ukrayna' },
  { city: 'Moscow', flag: '🇷🇺', label: 'Moskova, Rusya' },
  { city: 'Saint Petersburg', flag: '🇷🇺', label: 'St. Petersburg, Rusya' },
  { city: 'Minsk', flag: '🇧🇾', label: 'Minsk, Belarus' },

  // ── AVRUPA — Güney
  { city: 'Athens', flag: '🇬🇷', label: 'Atina, Yunanistan' },
  { city: 'Thessaloniki', flag: '🇬🇷', label: 'Selanik, Yunanistan' },
  { city: 'Santorini', flag: '🇬🇷', label: 'Santorini, Yunanistan' },
  { city: 'Mykonos', flag: '🇬🇷', label: 'Mikonos, Yunanistan' },
  { city: 'Rhodes', flag: '🇬🇷', label: 'Rodos, Yunanistan' },
  { city: 'Crete', flag: '🇬🇷', label: 'Girit, Yunanistan' },
  { city: 'Skopje', flag: '🇲🇰', label: 'Üsküp, Kuzey Makedonya' },
  { city: 'Tirana', flag: '🇦🇱', label: 'Tiran, Arnavutluk' },
  { city: 'Podgorica', flag: '🇲🇪', label: 'Podgorica, Karadağ' },
  { city: 'Kotor', flag: '🇲🇪', label: 'Kotor, Karadağ' },
  { city: 'Sarajevo', flag: '🇧🇦', label: 'Saraybosna, Bosna Hersek' },
  { city: 'Valletta', flag: '🇲🇹', label: 'Valletta, Malta' },
  { city: 'Nicosia', flag: '🇨🇾', label: 'Lefkoşa, Kıbrıs' },

  // ── ORTA DOĞU
  { city: 'Dubai', flag: '🇦🇪', label: 'Dubai, BAE' },
  { city: 'Abu Dhabi', flag: '🇦🇪', label: 'Abu Dabi, BAE' },
  { city: 'Doha', flag: '🇶🇦', label: 'Doha, Katar' },
  { city: 'Riyadh', flag: '🇸🇦', label: 'Riyad, Suudi Arabistan' },
  { city: 'Jeddah', flag: '🇸🇦', label: 'Cidde, Suudi Arabistan' },
  { city: 'Muscat', flag: '🇴🇲', label: 'Maskat, Umman' },
  { city: 'Kuwait City', flag: '🇰🇼', label: 'Kuveyt, Kuveyt' },
  { city: 'Manama', flag: '🇧🇭', label: 'Manama, Bahreyn' },
  { city: 'Beirut', flag: '🇱🇧', label: 'Beyrut, Lübnan' },
  { city: 'Amman', flag: '🇯🇴', label: 'Amman, Ürdün' },
  { city: 'Tel Aviv', flag: '🇮🇱', label: 'Tel Aviv, İsrail' },
  { city: 'Jerusalem', flag: '🇮🇱', label: 'Kudüs, İsrail' },
  { city: 'Tehran', flag: '🇮🇷', label: 'Tahran, İran' },
  { city: 'Baghdad', flag: '🇮🇶', label: 'Bağdat, Irak' },

  // ── GÜNEY ASYA
  { city: 'New Delhi', flag: '🇮🇳', label: 'Yeni Delhi, Hindistan' },
  { city: 'Mumbai', flag: '🇮🇳', label: 'Mumbai, Hindistan' },
  { city: 'Bangalore', flag: '🇮🇳', label: 'Bangalore, Hindistan' },
  { city: 'Chennai', flag: '🇮🇳', label: 'Chennai, Hindistan' },
  { city: 'Kolkata', flag: '🇮🇳', label: 'Kalküta, Hindistan' },
  { city: 'Goa', flag: '🇮🇳', label: 'Goa, Hindistan' },
  { city: 'Jaipur', flag: '🇮🇳', label: 'Jaipur, Hindistan' },
  { city: 'Agra', flag: '🇮🇳', label: 'Agra, Hindistan' },
  { city: 'Islamabad', flag: '🇵🇰', label: 'İslamabad, Pakistan' },
  { city: 'Karachi', flag: '🇵🇰', label: 'Karaçi, Pakistan' },
  { city: 'Lahore', flag: '🇵🇰', label: 'Lahor, Pakistan' },
  { city: 'Dhaka', flag: '🇧🇩', label: 'Dakka, Bangladeş' },
  { city: 'Colombo', flag: '🇱🇰', label: 'Kolombo, Sri Lanka' },
  { city: 'Kathmandu', flag: '🇳🇵', label: 'Katmandu, Nepal' },
  { city: 'Male', flag: '🇲🇻', label: 'Male, Maldivler' },

  // ── DOĞU ASYA
  { city: 'Tokyo', flag: '🇯🇵', label: 'Tokyo, Japonya' },
  { city: 'Osaka', flag: '🇯🇵', label: 'Osaka, Japonya' },
  { city: 'Kyoto', flag: '🇯🇵', label: 'Kyoto, Japonya' },
  { city: 'Hiroshima', flag: '🇯🇵', label: 'Hiroşima, Japonya' },
  { city: 'Sapporo', flag: '🇯🇵', label: 'Sapporo, Japonya' },
  { city: 'Beijing', flag: '🇨🇳', label: 'Pekin, Çin' },
  { city: 'Shanghai', flag: '🇨🇳', label: 'Şanghay, Çin' },
  { city: 'Guangzhou', flag: '🇨🇳', label: 'Guangzhou, Çin' },
  { city: 'Chengdu', flag: '🇨🇳', label: 'Chengdu, Çin' },
  { city: 'Xi\'an', flag: '🇨🇳', label: "Xi'an, Çin" },
  { city: 'Hong Kong', flag: '🇭🇰', label: 'Hong Kong' },
  { city: 'Macau', flag: '🇲🇴', label: 'Makao' },
  { city: 'Seoul', flag: '🇰🇷', label: 'Seul, Güney Kore' },
  { city: 'Busan', flag: '🇰🇷', label: 'Busan, Güney Kore' },
  { city: 'Jeju', flag: '🇰🇷', label: 'Jeju, Güney Kore' },
  { city: 'Taipei', flag: '🇹🇼', label: 'Taipei, Tayvan' },
  { city: 'Ulaanbaatar', flag: '🇲🇳', label: 'Ulan Batur, Moğolistan' },

  // ── GÜNEYDOĞU ASYA
  { city: 'Bangkok', flag: '🇹🇭', label: 'Bangkok, Tayland' },
  { city: 'Phuket', flag: '🇹🇭', label: 'Phuket, Tayland' },
  { city: 'Chiang Mai', flag: '🇹🇭', label: 'Chiang Mai, Tayland' },
  { city: 'Pattaya', flag: '🇹🇭', label: 'Pattaya, Tayland' },
  { city: 'Singapore', flag: '🇸🇬', label: 'Singapur' },
  { city: 'Kuala Lumpur', flag: '🇲🇾', label: 'Kuala Lumpur, Malezya' },
  { city: 'Penang', flag: '🇲🇾', label: 'Penang, Malezya' },
  { city: 'Jakarta', flag: '🇮🇩', label: 'Cakarta, Endonezya' },
  { city: 'Bali', flag: '🇮🇩', label: 'Bali, Endonezya' },
  { city: 'Lombok', flag: '🇮🇩', label: 'Lombok, Endonezya' },
  { city: 'Yogyakarta', flag: '🇮🇩', label: 'Yogyakarta, Endonezya' },
  { city: 'Manila', flag: '🇵🇭', label: 'Manila, Filipinler' },
  { city: 'Cebu', flag: '🇵🇭', label: 'Cebu, Filipinler' },
  { city: 'Boracay', flag: '🇵🇭', label: 'Boracay, Filipinler' },
  { city: 'Hanoi', flag: '🇻🇳', label: 'Hanoi, Vietnam' },
  { city: 'Ho Chi Minh City', flag: '🇻🇳', label: 'Ho Chi Minh, Vietnam' },
  { city: 'Da Nang', flag: '🇻🇳', label: 'Da Nang, Vietnam' },
  { city: 'Hoi An', flag: '🇻🇳', label: 'Hoi An, Vietnam' },
  { city: 'Phnom Penh', flag: '🇰🇭', label: 'Phnom Penh, Kamboçya' },
  { city: 'Siem Reap', flag: '🇰🇭', label: 'Siem Reap, Kamboçya' },
  { city: 'Vientiane', flag: '🇱🇦', label: 'Vientiane, Laos' },
  { city: 'Yangon', flag: '🇲🇲', label: 'Yangon, Myanmar' },
  { city: 'Naypyidaw', flag: '🇲🇲', label: 'Naypyidaw, Myanmar' },
  { city: 'Colombo', flag: '🇱🇰', label: 'Kolombo, Sri Lanka' },
  { city: 'Bandar Seri Begawan', flag: '🇧🇳', label: 'Brunei' },
  { city: 'Dili', flag: '🇹🇱', label: 'Dili, Doğu Timor' },

  // ── ORTA ASYA & KAFKASYA
  { city: 'Tashkent', flag: '🇺🇿', label: 'Taşkent, Özbekistan' },
  { city: 'Samarkand', flag: '🇺🇿', label: 'Semerkant, Özbekistan' },
  { city: 'Almaty', flag: '🇰🇿', label: 'Almatı, Kazakistan' },
  { city: 'Nur-Sultan', flag: '🇰🇿', label: 'Astana, Kazakistan' },
  { city: 'Bishkek', flag: '🇰🇬', label: 'Bişkek, Kırgızistan' },
  { city: 'Dushanbe', flag: '🇹🇯', label: 'Duşanbe, Tacikistan' },
  { city: 'Ashgabat', flag: '🇹🇲', label: 'Aşkabat, Türkmenistan' },
  { city: 'Baku', flag: '🇦🇿', label: 'Bakü, Azerbaycan' },
  { city: 'Tbilisi', flag: '🇬🇪', label: 'Tiflis, Gürcistan' },
  { city: 'Batumi', flag: '🇬🇪', label: 'Batum, Gürcistan' },
  { city: 'Yerevan', flag: '🇦🇲', label: 'Erivan, Ermenistan' },

  // ── AFRİKA — Kuzey
  { city: 'Cairo', flag: '🇪🇬', label: 'Kahire, Mısır' },
  { city: 'Alexandria', flag: '🇪🇬', label: 'İskenderiye, Mısır' },
  { city: 'Sharm el-Sheikh', flag: '🇪🇬', label: 'Şarm el-Şeyh, Mısır' },
  { city: 'Hurghada', flag: '🇪🇬', label: 'Hurgada, Mısır' },
  { city: 'Marrakech', flag: '🇲🇦', label: 'Marakeş, Fas' },
  { city: 'Casablanca', flag: '🇲🇦', label: 'Kazablanka, Fas' },
  { city: 'Fes', flag: '🇲🇦', label: 'Fes, Fas' },
  { city: 'Rabat', flag: '🇲🇦', label: 'Rabat, Fas' },
  { city: 'Tunis', flag: '🇹🇳', label: 'Tunus, Tunus' },
  { city: 'Djerba', flag: '🇹🇳', label: 'Cerbe, Tunus' },
  { city: 'Algiers', flag: '🇩🇿', label: 'Cezayir, Cezayir' },
  { city: 'Tripoli', flag: '🇱🇾', label: 'Trablus, Libya' },
  { city: 'Khartoum', flag: '🇸🇩', label: 'Hartum, Sudan' },
  { city: 'Addis Ababa', flag: '🇪🇹', label: 'Addis Ababa, Etiyopya' },

  // ── AFRİKA — Doğu & Güney
  { city: 'Nairobi', flag: '🇰🇪', label: 'Nairobi, Kenya' },
  { city: 'Mombasa', flag: '🇰🇪', label: 'Mombasa, Kenya' },
  { city: 'Dar es Salaam', flag: '🇹🇿', label: 'Dar es Selam, Tanzanya' },
  { city: 'Zanzibar', flag: '🇹🇿', label: 'Zanzibar, Tanzanya' },
  { city: 'Kampala', flag: '🇺🇬', label: 'Kampala, Uganda' },
  { city: 'Kigali', flag: '🇷🇼', label: 'Kigali, Ruanda' },
  { city: 'Johannesburg', flag: '🇿🇦', label: 'Johannesburg, G. Afrika' },
  { city: 'Cape Town', flag: '🇿🇦', label: 'Cape Town, Güney Afrika' },
  { city: 'Durban', flag: '🇿🇦', label: 'Durban, Güney Afrika' },
  { city: 'Pretoria', flag: '🇿🇦', label: 'Pretoria, Güney Afrika' },
  { city: 'Windhoek', flag: '🇳🇦', label: 'Windhoek, Namibya' },
  { city: 'Gaborone', flag: '🇧🇼', label: 'Gaborone, Botsvana' },
  { city: 'Harare', flag: '🇿🇼', label: 'Harare, Zimbabve' },
  { city: 'Lusaka', flag: '🇿🇲', label: 'Lusaka, Zambiya' },
  { city: 'Antananarivo', flag: '🇲🇬', label: 'Antananarivo, Madagaskar' },
  { city: 'Port Louis', flag: '🇲🇺', label: 'Port Louis, Mauritius' },
  { city: 'Victoria', flag: '🇸🇨', label: 'Victoria, Seyşeller' },

  // ── AFRİKA — Batı & Orta
  { city: 'Lagos', flag: '🇳🇬', label: 'Lagos, Nijerya' },
  { city: 'Abuja', flag: '🇳🇬', label: 'Abuja, Nijerya' },
  { city: 'Accra', flag: '🇬🇭', label: 'Akra, Gana' },
  { city: 'Dakar', flag: '🇸🇳', label: 'Dakar, Senegal' },
  { city: 'Abidjan', flag: '🇨🇮', label: 'Abidjan, Fildişi Sahili' },
  { city: 'Kinshasa', flag: '🇨🇩', label: 'Kinşasa, Kongo' },
  { city: 'Luanda', flag: '🇦🇴', label: 'Luanda, Angola' },
  { city: 'Douala', flag: '🇨🇲', label: 'Duala, Kamerun' },

  // ── KUZEY AMERİKA
  { city: 'New York', flag: '🇺🇸', label: 'New York, ABD' },
  { city: 'Los Angeles', flag: '🇺🇸', label: 'Los Angeles, ABD' },
  { city: 'Chicago', flag: '🇺🇸', label: 'Chicago, ABD' },
  { city: 'Miami', flag: '🇺🇸', label: 'Miami, ABD' },
  { city: 'San Francisco', flag: '🇺🇸', label: 'San Francisco, ABD' },
  { city: 'Las Vegas', flag: '🇺🇸', label: 'Las Vegas, ABD' },
  { city: 'Washington', flag: '🇺🇸', label: 'Washington D.C., ABD' },
  { city: 'Boston', flag: '🇺🇸', label: 'Boston, ABD' },
  { city: 'Seattle', flag: '🇺🇸', label: 'Seattle, ABD' },
  { city: 'Houston', flag: '🇺🇸', label: 'Houston, ABD' },
  { city: 'Dallas', flag: '🇺🇸', label: 'Dallas, ABD' },
  { city: 'Atlanta', flag: '🇺🇸', label: 'Atlanta, ABD' },
  { city: 'Denver', flag: '🇺🇸', label: 'Denver, ABD' },
  { city: 'Phoenix', flag: '🇺🇸', label: 'Phoenix, ABD' },
  { city: 'New Orleans', flag: '🇺🇸', label: 'New Orleans, ABD' },
  { city: 'Nashville', flag: '🇺🇸', label: 'Nashville, ABD' },
  { city: 'Orlando', flag: '🇺🇸', label: 'Orlando, ABD' },
  { city: 'Honolulu', flag: '🇺🇸', label: 'Honolulu, Hawaii, ABD' },
  { city: 'Anchorage', flag: '🇺🇸', label: 'Anchorage, Alaska, ABD' },
  { city: 'Toronto', flag: '🇨🇦', label: 'Toronto, Kanada' },
  { city: 'Vancouver', flag: '🇨🇦', label: 'Vancouver, Kanada' },
  { city: 'Montreal', flag: '🇨🇦', label: 'Montreal, Kanada' },
  { city: 'Calgary', flag: '🇨🇦', label: 'Calgary, Kanada' },
  { city: 'Ottawa', flag: '🇨🇦', label: 'Ottawa, Kanada' },
  { city: 'Quebec City', flag: '🇨🇦', label: 'Quebec, Kanada' },
  { city: 'Mexico City', flag: '🇲🇽', label: 'Mexico City, Meksika' },
  { city: 'Cancun', flag: '🇲🇽', label: 'Cancun, Meksika' },
  { city: 'Guadalajara', flag: '🇲🇽', label: 'Guadalajara, Meksika' },
  { city: 'Tulum', flag: '🇲🇽', label: 'Tulum, Meksika' },
  { city: 'Havana', flag: '🇨🇺', label: 'Havana, Küba' },
  { city: 'Kingston', flag: '🇯🇲', label: 'Kingston, Jamaika' },
  { city: 'Nassau', flag: '🇧🇸', label: 'Nassau, Bahamalar' },
  { city: 'Bridgetown', flag: '🇧🇧', label: 'Bridgetown, Barbados' },
  { city: 'San Juan', flag: '🇵🇷', label: 'San Juan, Porto Riko' },
  { city: 'Punta Cana', flag: '🇩🇴', label: 'Punta Cana, Dominik Cumh.' },
  { city: 'Guatemala City', flag: '🇬🇹', label: 'Guatemala City, Guatemala' },
  { city: 'San Jose', flag: '🇨🇷', label: 'San Jose, Kosta Rika' },
  { city: 'Panama City', flag: '🇵🇦', label: 'Panama City, Panama' },

  // ── GÜNEY AMERİKA
  { city: 'Sao Paulo', flag: '🇧🇷', label: 'São Paulo, Brezilya' },
  { city: 'Rio de Janeiro', flag: '🇧🇷', label: 'Rio de Janeiro, Brezilya' },
  { city: 'Brasilia', flag: '🇧🇷', label: 'Brasília, Brezilya' },
  { city: 'Salvador', flag: '🇧🇷', label: 'Salvador, Brezilya' },
  { city: 'Florianopolis', flag: '🇧🇷', label: 'Florianópolis, Brezilya' },
  { city: 'Buenos Aires', flag: '🇦🇷', label: 'Buenos Aires, Arjantin' },
  { city: 'Mendoza', flag: '🇦🇷', label: 'Mendoza, Arjantin' },
  { city: 'Bariloche', flag: '🇦🇷', label: 'Bariloche, Arjantin' },
  { city: 'Santiago', flag: '🇨🇱', label: 'Santiago, Şili' },
  { city: 'Valparaiso', flag: '🇨🇱', label: 'Valparaíso, Şili' },
  { city: 'Lima', flag: '🇵🇪', label: 'Lima, Peru' },
  { city: 'Cusco', flag: '🇵🇪', label: 'Cusco, Peru' },
  { city: 'Bogota', flag: '🇨🇴', label: 'Bogotá, Kolombiya' },
  { city: 'Medellin', flag: '🇨🇴', label: 'Medellín, Kolombiya' },
  { city: 'Cartagena', flag: '🇨🇴', label: 'Cartagena, Kolombiya' },
  { city: 'Quito', flag: '🇪🇨', label: 'Quito, Ekvador' },
  { city: 'Galapagos', flag: '🇪🇨', label: 'Galapagos, Ekvador' },
  { city: 'Caracas', flag: '🇻🇪', label: 'Karakas, Venezuela' },
  { city: 'La Paz', flag: '🇧🇴', label: 'La Paz, Bolivya' },
  { city: 'Asuncion', flag: '🇵🇾', label: 'Asunción, Paraguay' },
  { city: 'Montevideo', flag: '🇺🇾', label: 'Montevideo, Uruguay' },
  { city: 'Georgetown', flag: '🇬🇾', label: 'Georgetown, Guyana' },
  { city: 'Paramaribo', flag: '🇸🇷', label: 'Paramaribo, Surinam' },

  // ── OKYANUSYA
  { city: 'Sydney', flag: '🇦🇺', label: 'Sidney, Avustralya' },
  { city: 'Melbourne', flag: '🇦🇺', label: 'Melbourne, Avustralya' },
  { city: 'Brisbane', flag: '🇦🇺', label: 'Brisbane, Avustralya' },
  { city: 'Perth', flag: '🇦🇺', label: 'Perth, Avustralya' },
  { city: 'Adelaide', flag: '🇦🇺', label: 'Adelaide, Avustralya' },
  { city: 'Gold Coast', flag: '🇦🇺', label: 'Gold Coast, Avustralya' },
  { city: 'Cairns', flag: '🇦🇺', label: 'Cairns, Avustralya' },
  { city: 'Auckland', flag: '🇳🇿', label: 'Auckland, Yeni Zelanda' },
  { city: 'Wellington', flag: '🇳🇿', label: 'Wellington, Yeni Zelanda' },
  { city: 'Queenstown', flag: '🇳🇿', label: 'Queenstown, Yeni Zelanda' },
  { city: 'Nadi', flag: '🇫🇯', label: 'Nadi, Fiji' },
  { city: 'Suva', flag: '🇫🇯', label: 'Suva, Fiji' },
  { city: 'Papeete', flag: '🇵🇫', label: 'Papeete, Fransız Polinezyası' },
  { city: 'Bora Bora', flag: '🇵🇫', label: 'Bora Bora, Fransız Polinezyası' },
  { city: 'Apia', flag: '🇼🇸', label: 'Apia, Samoa' },
  { city: 'Nuku\'alofa', flag: '🇹🇴', label: "Nuku'alofa, Tonga" },
  { city: 'Honiara', flag: '🇸🇧', label: 'Honiara, Solomon Adaları' },
  { city: 'Port Moresby', flag: '🇵🇬', label: 'Port Moresby, Papua Yeni Gine' },
  { city: 'Noumea', flag: '🇳🇨', label: 'Noumea, Yeni Kaledonya' },
];
